server:
  port: 8090

google:
  recaptcha:
    url: https://www.google.com/recaptcha/api/siteverify
    key: ${GOOGLE_RECAPTCHA_KEY}
    secret: ${GOOGLE_RECAPTCHA_SECRET}
logging:
  level:
    root: info
    org.springframework.web: debug
